version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: agentsfood
      POSTGRES_USER: agentsfood
      POSTGRES_PASSWORD: agentsfood123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agentsfood-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agentsfood-network

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://agentsfood:agentsfood123@postgres:5432/agentsfood
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      WHATSAPP_TOKEN: your-whatsapp-token
      OPENAI_API_KEY: your-openai-api-key
    depends_on:
      - postgres
      - redis
    networks:
      - agentsfood-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXTAUTH_SECRET: your-super-secret-nextauth-key-change-in-production
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - agentsfood-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  agentsfood-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: